### ISSUE TITLE
Cannot compose container create-beacon-chain-genesis

### ISSUE THREAD

**Issue by dewindtk** [OffchainLabs/eth-pos-devnet#36]
Hi. Just tried running the containers but there seems to be an error in  create-beacon-chain-genesis. Here iis what the logs say. Please let me know if there is a known fix to this issue. 

2023-09-10 23:27:32 time="2023-09-10T21:27:32Z" level=info msg="No genesis time specified, defaulting to now()" prefix=genesis
2023-09-10 23:27:32 time="2023-09-10T21:27:32Z" level=info msg="Delaying genesis 1694381252 by 15 seconds" prefix=genesis
2023-09-10 23:27:32 time="2023-09-10T21:27:32Z" level=info msg="Genesis is now 1694381267" prefix=genesis
2023-09-10 23:27:32 panic: runtime error: invalid memory address or nil pointer dereference
2023-09-10 23:27:32 [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2d0503f]
2023-09-10 23:27:32 
2023-09-10 23:27:32 goroutine 1 [running]:
2023-09-10 23:27:32 github.com/prysmaticlabs/prysm/v4/cmd/prysmctl/testnet.generateGenesis({0xcfacd0, 0xc000126000})
2023-09-10 23:27:32     cmd/prysmctl/testnet/generate_genesis.go:279 +0x6ff
2023-09-10 23:27:32 github.com/prysmaticlabs/prysm/v4/cmd/prysmctl/testnet.cliActionGenerateGenesisState(0xc000934500)
2023-09-10 23:27:32     cmd/prysmctl/testnet/generate_genesis.go:179 +0x1c9
2023-09-10 23:27:32 github.com/prysmaticlabs/prysm/v4/cmd/prysmctl/testnet.glob..func1(0x2fad200?)
2023-09-10 23:27:32     cmd/prysmctl/testnet/generate_genesis.go:70 +0x2e
2023-09-10 23:27:32 github.com/urfave/cli/v2.(*Command).Run(0x2fad200, 0xc000934500, {0xc00013d880, 0x8, 0x8})
2023-09-10 23:27:32     external/com_github_urfave_cli_v2/command.go:274 +0x9eb
2023-09-10 23:27:32 github.com/urfave/cli/v2.(*Command).Run(0x2fad0a0, 0xc000934440, {0xc0000d65a0, 0x9, 0x9})
2023-09-10 23:27:32     external/com_github_urfave_cli_v2/command.go:267 +0xc4d
2023-09-10 23:27:32 github.com/urfave/cli/v2.(*Command).Run(0xc000546000, 0xc000934380, {0xc000124000, 0xa, 0xa})
2023-09-10 23:27:32     external/com_github_urfave_cli_v2/command.go:267 +0xc4d
2023-09-10 23:27:32 github.com/urfave/cli/v2.(*App).RunContext(0xc00049cb40, {0xcfacd0?, 0xc000126000}, {0xc000124000, 0xa, 0xa})
2023-09-10 23:27:32     external/com_github_urfave_cli_v2/app.go:332 +0x616
2023-09-10 23:27:32 github.com/urfave/cli/v2.(*App).Run(...)
2023-09-10 23:27:32     external/com_github_urfave_cli_v2/app.go:309
2023-09-10 23:27:32 main.main()
2023-09-10 23:27:32     cmd/prysmctl/main.go:23 +0x8e

**Comment by dewindtk** [comment]
Incredible. Thanks for taking the effort of going through all images. Cheers, my network is up.

**Comment by lirc571** [comment]
This issue still exists. Perhaps we should keep it open? Using an old build should not be the final solution.

**Comment by dewindtk** [comment]
I agree. Also there are a lott of things out of date in this tutorial. I request for an update!

**Comment by rzmahmood** [comment]
I found the issue to be fairly non-deterministic. I reran it a few times and somehow it worked...

**Comment by rzmahmood** [comment]
I've made my own version which doesn't rely on docker, as I prefer using local versions I can quickly modify. You may find it useful

https://github.com/rzmahmood/ethereum-pos-testnet/tree/main
